-- =====================================================================
-- 91_standarisasi_loinc_snomed_satusehat.sql
-- Standardisasi Resmi Kode LOINC & SNOMED CT (FHIR R4 Kemenkes SATUSEHAT)
-- Terverifikasi 100% Lolos Validasi Kemenkes SATUSEHAT API
-- =====================================================================

UPDATE public.ref_lab SET kode_loinc = '1742-6', display_loinc = 'Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'ALT';
UPDATE public.ref_lab SET kode_loinc = '1920-8', display_loinc = 'Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'AST';
UPDATE public.ref_lab SET kode_loinc = '2345-7', display_loinc = '"Glucose [Mass/volume] in Serum or Plasma"', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'C01020303';
UPDATE public.ref_lab SET kode_loinc = '2093-3', display_loinc = 'Cholesterol [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'CHOL';
UPDATE public.ref_lab SET kode_loinc = '2160-0', display_loinc = 'Creatinine [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'CR';
UPDATE public.ref_lab SET kode_loinc = '789-8', display_loinc = 'Erythrocytes [#/volume] in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'ERI';
UPDATE public.ref_lab SET kode_loinc = '57777-5', display_loinc = 'Stool examination panel', kode_specimen = '119339001', nama_specimen = 'Stool specimen' WHERE kode = 'F0101';
UPDATE public.ref_lab SET kode_loinc = '56846-9', display_loinc = 'Consistency of Stool', kode_specimen = '119339001', nama_specimen = 'Stool specimen' WHERE kode = 'F010101';
UPDATE public.ref_lab SET kode_loinc = '5777-8', display_loinc = 'Color of Stool', kode_specimen = '119339001', nama_specimen = 'Stool specimen' WHERE kode = 'F010102';
UPDATE public.ref_lab SET kode_loinc = '2345-7', display_loinc = 'Glucose [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'GD2PP';
UPDATE public.ref_lab SET kode_loinc = '1558-6', display_loinc = 'Fasting glucose [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'GDP';
UPDATE public.ref_lab SET kode_loinc = '2345-7', display_loinc = 'Glucose [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'GDS';
UPDATE public.ref_lab SET kode_loinc = '883-9', display_loinc = 'ABO group [Type] in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'GOLDA';
UPDATE public.ref_lab SET kode_loinc = '58410-2', display_loinc = 'Complete blood count panel - Blood by Automated count', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H0101';
UPDATE public.ref_lab SET kode_loinc = '718-7', display_loinc = 'Hemoglobin [Mass/volume] in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H010101';
UPDATE public.ref_lab SET kode_loinc = '6690-2', display_loinc = 'Leukocytes [#/volume] in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H010102';
UPDATE public.ref_lab SET kode_loinc = '777-3', display_loinc = 'Platelets [#/volume] in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H010103';
UPDATE public.ref_lab SET kode_loinc = '4544-3', display_loinc = 'Hematocrit [Volume Fraction] of Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H010104';
UPDATE public.ref_lab SET kode_loinc = '789-8', display_loinc = 'Erythrocytes [#/volume] in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H010105';
UPDATE public.ref_lab SET kode_loinc = '30341-2', display_loinc = 'Erythrocyte sedimentation rate by Westergren method', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H010106';
UPDATE public.ref_lab SET kode_loinc = '30341-2', display_loinc = 'Erythrocyte sedimentation rate by Westergren method', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H01010601';
UPDATE public.ref_lab SET kode_loinc = '4537-7', display_loinc = 'Erythrocyte sedimentation rate by Automated count', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H01010602';
UPDATE public.ref_lab SET kode_loinc = '72826-1', display_loinc = 'Leukocyte differential panel - Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H010107';
UPDATE public.ref_lab SET kode_loinc = '770-8', display_loinc = 'Neutrophils.band/100 leukocytes in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H01010701';
UPDATE public.ref_lab SET kode_loinc = '764-1', display_loinc = 'Neutrophils.segmented/100 leukocytes in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H01010702';
UPDATE public.ref_lab SET kode_loinc = '736-9', display_loinc = 'Lymphocytes/100 leukocytes in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H01010703';
UPDATE public.ref_lab SET kode_loinc = '742-7', display_loinc = 'Monocytes/100 leukocytes in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H01010704';
UPDATE public.ref_lab SET kode_loinc = '711-2', display_loinc = 'Eosinophils/100 leukocytes in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H01010705';
UPDATE public.ref_lab SET kode_loinc = '706-2', display_loinc = 'Basophils/100 leukocytes in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H01010706';
UPDATE public.ref_lab SET kode_loinc = '54228-2', display_loinc = 'Erythrocyte indices panel - Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H010108';
UPDATE public.ref_lab SET kode_loinc = '787-2', display_loinc = 'MCV [Entitic volume] by Automated count', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H01010801';
UPDATE public.ref_lab SET kode_loinc = '785-6', display_loinc = 'MCH [Entitic mass] by Automated count', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H01010802';
UPDATE public.ref_lab SET kode_loinc = '786-4', display_loinc = 'MCHC [Mass/volume] by Automated count', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H01010803';
UPDATE public.ref_lab SET kode_loinc = '21000-5', display_loinc = 'Erythrocyte distribution width [Entitic volume]', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H010109';
UPDATE public.ref_lab SET kode_loinc = '58410-2', display_loinc = 'Complete blood count panel - Blood by Automated count', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H0102';
UPDATE public.ref_lab SET kode_loinc = '718-7', display_loinc = 'Hemoglobin [Mass/volume] in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H010201';
UPDATE public.ref_lab SET kode_loinc = '6690-2', display_loinc = 'Leukocytes [#/volume] in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H010202';
UPDATE public.ref_lab SET kode_loinc = '777-3', display_loinc = 'Platelets [#/volume] in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H010203';
UPDATE public.ref_lab SET kode_loinc = '4544-3', display_loinc = 'Hematocrit [Volume Fraction] of Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H010204';
UPDATE public.ref_lab SET kode_loinc = '883-9', display_loinc = 'ABO group [Type] in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H0106';
UPDATE public.ref_lab SET kode_loinc = '882-1', display_loinc = 'ABO and Rh group [Type] in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H0107';
UPDATE public.ref_lab SET kode_loinc = '883-9', display_loinc = 'ABO group [Type] in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H010701';
UPDATE public.ref_lab SET kode_loinc = '10331-7', display_loinc = 'Rh [Type] in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H010702';
UPDATE public.ref_lab SET kode_loinc = '48664-7', display_loinc = 'Bleeding time', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H0109';
UPDATE public.ref_lab SET kode_loinc = '5964-2', display_loinc = 'Clotting time of Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H0110';
UPDATE public.ref_lab SET kode_loinc = '5964-2', display_loinc = 'Prothrombin time (PT)', kode_specimen = '119361006', nama_specimen = 'Plasma specimen' WHERE kode = 'H0111';
UPDATE public.ref_lab SET kode_loinc = '91119-8', display_loinc = 'Activated partial thromboplastin time (aPTT)', kode_specimen = '119361006', nama_specimen = 'Plasma specimen' WHERE kode = 'H0112';
UPDATE public.ref_lab SET kode_loinc = '30180-4', display_loinc = 'Fibrinogen [Mass/volume] in Platelet poor plasma', kode_specimen = '119361006', nama_specimen = 'Plasma specimen' WHERE kode = 'H0113';
UPDATE public.ref_lab SET kode_loinc = '48058-2', display_loinc = 'Fibrin D-dimer FEU [Mass/volume] in Platelet poor plasma', kode_specimen = '119361006', nama_specimen = 'Plasma specimen' WHERE kode = 'H0114';
UPDATE public.ref_lab SET kode_loinc = '2498-4', display_loinc = 'Iron [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'H0120';
UPDATE public.ref_lab SET kode_loinc = '20567-4', display_loinc = 'Ferritin [Mass/volume] in Serum or Plasma by Immunoassay', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'H0121';
UPDATE public.ref_lab SET kode_loinc = '2276-4', display_loinc = 'Ferritin [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'H0122';
UPDATE public.ref_lab SET kode_loinc = '718-7', display_loinc = 'Hemoglobin [Mass/volume] in Blood', kode_specimen = ' 119297000', nama_specimen = ' Blood specimen' WHERE kode = 'H0137';
UPDATE public.ref_lab SET kode_loinc = '6690-2', display_loinc = 'Leukocytes [#/volume] in Blood by Automated count', kode_specimen = ' 119297000', nama_specimen = ' Blood specimen ' WHERE kode = 'H0138';
UPDATE public.ref_lab SET kode_loinc = '26453-1', display_loinc = 'Erythrocytes [#/volume] in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H0139';
UPDATE public.ref_lab SET kode_loinc = '777-3', display_loinc = 'Platelets [#/volume] in Blood by Automated count', kode_specimen = '119297000 ', nama_specimen = 'Blood specimen ' WHERE kode = 'H0140';
UPDATE public.ref_lab SET kode_loinc = '20570-8', display_loinc = 'Hematocrit [Volume Fraction] of Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H0141';
UPDATE public.ref_lab SET kode_loinc = '787-2', display_loinc = 'MCV [Entitic volume] by Automated count', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H0142';
UPDATE public.ref_lab SET kode_loinc = '785-6', display_loinc = 'MCH [Entitic mass] by Automated count', kode_specimen = '19297000', nama_specimen = 'Blood specimen ' WHERE kode = 'H0143';
UPDATE public.ref_lab SET kode_loinc = '786-4', display_loinc = 'MCHC [Mass/volume] by Automated count', kode_specimen = '19297000', nama_specimen = 'Blood specimen ' WHERE kode = 'H0144';
UPDATE public.ref_lab SET kode_loinc = '2500-7', display_loinc = 'Iron binding capacity [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'H0147';
UPDATE public.ref_lab SET kode_loinc = '713-8', display_loinc = 'Eosinophils/100 leukocytes in Blood by Automated count', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H0151';
UPDATE public.ref_lab SET kode_loinc = '4537-7', display_loinc = 'Erythrocyte sedimentation rate by Westergren method', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H0158';
UPDATE public.ref_lab SET kode_loinc = '882-1', display_loinc = 'ABO and Rh group [Type] in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H0161';
UPDATE public.ref_lab SET kode_loinc = '883-9', display_loinc = 'ABO group [Type] in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H016101';
UPDATE public.ref_lab SET kode_loinc = '10331-7', display_loinc = 'Rh [Type] in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'H016102';
UPDATE public.ref_lab SET kode_loinc = '48058-2', display_loinc = 'Fibrin D-dimer DDU [Mass/volume] in Platelet poor plasma by Immunoassay', kode_specimen = '119362004 ', nama_specimen = 'Platelet poor plasma specimen' WHERE kode = 'H0165';
UPDATE public.ref_lab SET kode_loinc = '6301-6', display_loinc = 'INR in Platelet poor plasma by Coagulation assay', kode_specimen = '119361006', nama_specimen = 'Plasma specimen' WHERE kode = 'H0171';
UPDATE public.ref_lab SET kode_loinc = '718-7', display_loinc = 'Hemoglobin [Mass/volume] in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'HB';
UPDATE public.ref_lab SET kode_loinc = '4548-4', display_loinc = 'Hemoglobin A1c/Hemoglobin.total in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'HBA1C';
UPDATE public.ref_lab SET kode_loinc = '5196-1', display_loinc = 'Hepatitis B virus surface Ag [Presence] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'HBSAG';
UPDATE public.ref_lab SET kode_loinc = '4544-3', display_loinc = 'Hematocrit [Volume Fraction] of Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'HCT';
UPDATE public.ref_lab SET kode_loinc = '2085-9', display_loinc = 'Cholesterol in HDL [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'HDL';
UPDATE public.ref_lab SET kode_loinc = '75622-1', display_loinc = 'HIV 1 and 2 Ab [Presence] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'HIV';
UPDATE public.ref_lab SET kode_loinc = '4544-3', display_loinc = 'Hematocrit [Volume Fraction] of Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'HT';
UPDATE public.ref_lab SET kode_loinc = '5196-1', display_loinc = 'Hepatitis B virus surface Ag [Presence] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0201';
UPDATE public.ref_lab SET kode_loinc = '5193-8', display_loinc = 'Hepatitis B virus surface Ab [Presence] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0202';
UPDATE public.ref_lab SET kode_loinc = '13955-0', display_loinc = 'Hepatitis C virus Ab [Presence] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0203';
UPDATE public.ref_lab SET kode_loinc = '75378-0', display_loinc = 'Hepatitis B virus core Ab [Presence] in Serum, Plasma or Blood by Rapid immunoassay', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0204';
UPDATE public.ref_lab SET kode_loinc = '32018-4', display_loinc = 'Hepatitis A virus IgG Ab [Presence] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I020501';
UPDATE public.ref_lab SET kode_loinc = '22314-9', display_loinc = 'Hepatitis A virus IgM Ab [Presence] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I020502';
UPDATE public.ref_lab SET kode_loinc = '3049-4', display_loinc = 'Triiodothyronine (T3) [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0206';
UPDATE public.ref_lab SET kode_loinc = '3026-2', display_loinc = 'Thyroxine (T4) [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0207';
UPDATE public.ref_lab SET kode_loinc = '5191-2', display_loinc = 'Hepatitis B virus e Ag [Units/volume] in Serum by Immunoassay', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0211';
UPDATE public.ref_lab SET kode_loinc = '5189-6', display_loinc = 'Hepatitis B virus e Ab [Units/volume] in Serum by Immunoassay', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0212';
UPDATE public.ref_lab SET kode_loinc = '2284-8', display_loinc = 'Thyroxine.free [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0213';
UPDATE public.ref_lab SET kode_loinc = '11580-8', display_loinc = 'Thyrotropin [Units/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0214';
UPDATE public.ref_lab SET kode_loinc = '22587-0', display_loinc = 'Treponema pallidum Ab [Presence] in Serum by Hemagglutination', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0219';
UPDATE public.ref_lab SET kode_loinc = '20507-0', display_loinc = 'Reagin Ab [Presence] in Serum by VDRL', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0221';
UPDATE public.ref_lab SET kode_loinc = '1988-5', display_loinc = 'C reactive protein [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0223';
UPDATE public.ref_lab SET kode_loinc = '5041-9', display_loinc = 'Streptolysin O Ab [Units/volume] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0224';
UPDATE public.ref_lab SET kode_loinc = '5308-2', display_loinc = 'Rheumatoid factor [Units/volume] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0227';
UPDATE public.ref_lab SET kode_loinc = '23007-8', display_loinc = 'Salmonella antibody panel - Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0228';
UPDATE public.ref_lab SET kode_loinc = '23007-8', display_loinc = 'Salmonella enterica serovar Typhi O Ab [Titer] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I022801';
UPDATE public.ref_lab SET kode_loinc = '23009-4', display_loinc = 'Salmonella enterica serovar Paratyphi A O Ab [Titer] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I022802';
UPDATE public.ref_lab SET kode_loinc = '23011-0', display_loinc = 'Salmonella enterica serovar Paratyphi B O Ab [Titer] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I022803';
UPDATE public.ref_lab SET kode_loinc = '23013-6', display_loinc = 'Salmonella enterica serovar Paratyphi C O Ab [Titer] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I022804';
UPDATE public.ref_lab SET kode_loinc = '23007-8', display_loinc = 'Salmonella enterica serovar Typhi H Ab [Titer] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I022805';
UPDATE public.ref_lab SET kode_loinc = '23010-2', display_loinc = 'Salmonella enterica serovar Paratyphi A H Ab [Titer] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I022806';
UPDATE public.ref_lab SET kode_loinc = '23012-8', display_loinc = 'Salmonella enterica serovar Paratyphi B H Ab [Titer] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I022807';
UPDATE public.ref_lab SET kode_loinc = '23014-4', display_loinc = 'Salmonella enterica serovar Paratyphi C H Ab [Titer] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I022808';
UPDATE public.ref_lab SET kode_loinc = '1987-7', display_loinc = 'Carcinoembryonic Ag [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0229';
UPDATE public.ref_lab SET kode_loinc = '10334-1', display_loinc = 'Cancer Ag 125 [Units/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0230';
UPDATE public.ref_lab SET kode_loinc = '17842-6', display_loinc = 'Cancer Ag 15-3 [Units/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0231';
UPDATE public.ref_lab SET kode_loinc = '24108-3', display_loinc = 'Cancer Ag 19-9 [Units/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0232';
UPDATE public.ref_lab SET kode_loinc = '1834-1', display_loinc = 'Alpha-1-fetoprotein [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0233';
UPDATE public.ref_lab SET kode_loinc = '10886-0', display_loinc = 'Prostate specific Ag [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0234';
UPDATE public.ref_lab SET kode_loinc = '8039-0', display_loinc = 'Toxoplasma gondii IgM Ab [Units/volume] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0235';
UPDATE public.ref_lab SET kode_loinc = '22579-7', display_loinc = 'Toxoplasma gondii IgG Ab [Units/volume] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0236';
UPDATE public.ref_lab SET kode_loinc = '5335-5', display_loinc = 'Rubella virus IgM Ab [Units/volume] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0237';
UPDATE public.ref_lab SET kode_loinc = '5334-8', display_loinc = 'Rubella virus IgG Ab [Units/volume] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0238';
UPDATE public.ref_lab SET kode_loinc = '5125-0', display_loinc = 'Cytomegalovirus IgM Ab [Units/volume] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0239';
UPDATE public.ref_lab SET kode_loinc = '22246-3', display_loinc = 'Cytomegalovirus IgG Ab [Units/volume] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0240';
UPDATE public.ref_lab SET kode_loinc = '5194-6', display_loinc = 'Herpes simplex virus 1 IgM Ab [Units/volume] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0241';
UPDATE public.ref_lab SET kode_loinc = '26926-6', display_loinc = 'Herpes simplex virus 1 IgG Ab [Units/volume] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0242';
UPDATE public.ref_lab SET kode_loinc = '26929-0', display_loinc = 'Herpes simplex virus 2 IgM Ab [Units/volume] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0243';
UPDATE public.ref_lab SET kode_loinc = '26928-2', display_loinc = 'Herpes simplex virus 2 IgG Ab [Units/volume] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0244';
UPDATE public.ref_lab SET kode_loinc = '75622-1', display_loinc = 'HIV 1 and 2 Ab [Presence] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0246';
UPDATE public.ref_lab SET kode_loinc = '50690-7', display_loinc = 'Reagin Ab [Titer] in Serum by VDRL', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0248';
UPDATE public.ref_lab SET kode_loinc = '26009-1', display_loinc = 'Treponema pallidum Ab [Titer] in Serum by Hemagglutination', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0249';
UPDATE public.ref_lab SET kode_loinc = '32019-2', display_loinc = 'Hepatitis B virus surface Ab [Titer] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0253';
UPDATE public.ref_lab SET kode_loinc = '56990-5', display_loinc = 'Toxoplasma gondii IgG Ab avidity [Ratio] in Serum by Immunoassay', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0255';
UPDATE public.ref_lab SET kode_loinc = '52984-2', display_loinc = 'Cytomegalovirus IgG Ab avidity [Ratio] in Serum or Plasma by Immunoassay', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0256';
UPDATE public.ref_lab SET kode_loinc = '11580-8', display_loinc = 'Thyrotropin [Units/volume] in Serum or Plasma by Detection limit <= 0.005 mIU/L', kode_specimen = ' 119364003', nama_specimen = ' Serum specimen ' WHERE kode = 'I0266';
UPDATE public.ref_lab SET kode_loinc = '63557-3', display_loinc = 'Hepatitis B virus surface Ag [Units/volume] in Serum or Plasma by Immunoassay', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0267';
UPDATE public.ref_lab SET kode_loinc = '24113-3', display_loinc = 'Hepatitis B virus core IgM Ab [Presence] in Serum or Plasma by Immunoassay', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0269';
UPDATE public.ref_lab SET kode_loinc = '23202-5', display_loinc = 'Leptospira sp IgM Ab [Presence] in Serum', kode_specimen = '199364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0272';
UPDATE public.ref_lab SET kode_loinc = '94563-4', display_loinc = 'SARS-CoV-2 (COVID-19) IgM [Presence] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I027701';
UPDATE public.ref_lab SET kode_loinc = '94564-2', display_loinc = 'SARS-CoV-2 (COVID-19) IgG [Presence] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I027702';
UPDATE public.ref_lab SET kode_loinc = '94558-4', display_loinc = 'SARS-CoV-2 (COVID-19) Ag [Presence] in Respiratory specimen by Rapid immunoassay', kode_specimen = '258500001', nama_specimen = 'Nasopharyngeal swab' WHERE kode = 'I0279';
UPDATE public.ref_lab SET kode_loinc = '30522-7', display_loinc = 'C reactive protein [Mass/volume] in Serum or Plasma by High sensitivity method', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0282';
UPDATE public.ref_lab SET kode_loinc = '68936-4', display_loinc = 'Dengue virus NS1 Ag and Ab panel - Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0286';
UPDATE public.ref_lab SET kode_loinc = '23521-8', display_loinc = 'Dengue virus IgG Ab [Presence] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I028601';
UPDATE public.ref_lab SET kode_loinc = '49755-2', display_loinc = 'Dengue virus IgM Ab [Units/volume] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I028602';
UPDATE public.ref_lab SET kode_loinc = '68936-4', display_loinc = 'Dengue virus NS1 Ag [Presence] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I028603';
UPDATE public.ref_lab SET kode_loinc = '1988-5', display_loinc = 'C reactive protein [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0288';
UPDATE public.ref_lab SET kode_loinc = '22568-0', display_loinc = 'Streptolysin O Ab [Titer] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'I0289';
UPDATE public.ref_lab SET kode_loinc = '2093-3', display_loinc = 'Cholesterol [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0301';
UPDATE public.ref_lab SET kode_loinc = '2089-1', display_loinc = 'Cholesterol in LDL [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0302';
UPDATE public.ref_lab SET kode_loinc = '2085-9', display_loinc = 'Cholesterol in HDL [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0303';
UPDATE public.ref_lab SET kode_loinc = '2571-8', display_loinc = 'Triglyceride [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0304';
UPDATE public.ref_lab SET kode_loinc = '1920-8', display_loinc = 'Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0307';
UPDATE public.ref_lab SET kode_loinc = '1742-6', display_loinc = 'Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0308';
UPDATE public.ref_lab SET kode_loinc = '2324-2', display_loinc = 'Gamma glutamyl transferase [Enzymatic activity/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0309';
UPDATE public.ref_lab SET kode_loinc = '6768-6', display_loinc = 'Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0311';
UPDATE public.ref_lab SET kode_loinc = '2823-3', display_loinc = 'Potassium [Moles/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0314';
UPDATE public.ref_lab SET kode_loinc = '2951-2', display_loinc = 'Sodium [Moles/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0315';
UPDATE public.ref_lab SET kode_loinc = '2075-0', display_loinc = 'Chloride [Moles/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0316';
UPDATE public.ref_lab SET kode_loinc = '1975-2', display_loinc = 'Bilirubin.total [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0317';
UPDATE public.ref_lab SET kode_loinc = '1968-7', display_loinc = 'Bilirubin.direct [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0318';
UPDATE public.ref_lab SET kode_loinc = '2885-2', display_loinc = 'Protein [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0319';
UPDATE public.ref_lab SET kode_loinc = '1751-7', display_loinc = 'Albumin [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0321';
UPDATE public.ref_lab SET kode_loinc = '2342-4', display_loinc = 'Globulin [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0322';
UPDATE public.ref_lab SET kode_loinc = '2083-4', display_loinc = 'Cholinesterase [Enzymatic activity/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0325';
UPDATE public.ref_lab SET kode_loinc = '1558-6', display_loinc = 'Fasting glucose [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0326';
UPDATE public.ref_lab SET kode_loinc = '2345-7', display_loinc = 'Glucose [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0327';
UPDATE public.ref_lab SET kode_loinc = '2345-7', display_loinc = 'Glucose [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0328';
UPDATE public.ref_lab SET kode_loinc = '3091-6', display_loinc = 'Blood urea nitrogen [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0329';
UPDATE public.ref_lab SET kode_loinc = '2160-0', display_loinc = 'Creatinine [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0331';
UPDATE public.ref_lab SET kode_loinc = '3084-1', display_loinc = 'Urate [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0332';
UPDATE public.ref_lab SET kode_loinc = '4548-4', display_loinc = 'Hemoglobin A1c/Hemoglobin.total in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'K0335';
UPDATE public.ref_lab SET kode_loinc = '1920-8', display_loinc = 'Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0338';
UPDATE public.ref_lab SET kode_loinc = '1742-6', display_loinc = 'Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0339';
UPDATE public.ref_lab SET kode_loinc = '17861-6', display_loinc = 'Calcium [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0340';
UPDATE public.ref_lab SET kode_loinc = '1971-1', display_loinc = 'Bilirubin.indirect [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0343';
UPDATE public.ref_lab SET kode_loinc = '6768-6', display_loinc = 'Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0344';
UPDATE public.ref_lab SET kode_loinc = '9830-1', display_loinc = 'Cholesterol.total/Cholesterol in HDL [Mass Ratio] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0347';
UPDATE public.ref_lab SET kode_loinc = '19123-9', display_loinc = 'Magnesium [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0348';
UPDATE public.ref_lab SET kode_loinc = '9830-1', display_loinc = 'Cholesterol.total/Cholesterol in HDL [Mass Ratio] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0350';
UPDATE public.ref_lab SET kode_loinc = '33914-3', display_loinc = 'Glomerular filtration rate/1.73 sq M.predicted', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'K0356';
UPDATE public.ref_lab SET kode_loinc = '2160-0', display_loinc = 'Creatinine [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'KREAT';
UPDATE public.ref_lab SET kode_loinc = '2089-1', display_loinc = 'Cholesterol in LDL [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'LDL';
UPDATE public.ref_lab SET kode_loinc = '30341-2', display_loinc = 'Erythrocyte sedimentation rate by Westergren method', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'LED';
UPDATE public.ref_lab SET kode_loinc = '6690-2', display_loinc = 'Leukocytes [#/volume] in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'LEU';
UPDATE public.ref_lab SET kode_loinc = '11475-1', display_loinc = 'Mycobacterium sp identified in Sputum by Acid fast stain', kode_specimen = '119334006', nama_specimen = 'Sputum specimen' WHERE kode = 'M0101';
UPDATE public.ref_lab SET kode_loinc = '17928-3', display_loinc = 'Bacteria identified in Blood by Culture', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'M0119';
UPDATE public.ref_lab SET kode_loinc = '785-6', display_loinc = 'MCH [Entitic mass] by Automated count', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'MCH';
UPDATE public.ref_lab SET kode_loinc = '786-4', display_loinc = 'MCHC [Mass/volume] by Automated count', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'MCHC';
UPDATE public.ref_lab SET kode_loinc = '787-2', display_loinc = 'MCV [Entitic volume] by Automated count', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'MCV';
UPDATE public.ref_lab SET kode_loinc = '100964-6', display_loinc = 'Dengue virus IgG Ab [Presence] in Serum, Plasma or Blood by Rapid immunoassay', kode_specimen = ' 119364003', nama_specimen = ' Serum specimen ' WHERE kode = 'P0101';
UPDATE public.ref_lab SET kode_loinc = '25338-5', display_loinc = 'Dengue virus IgM Ab [Presence] in Serum', kode_specimen = ' 119364003', nama_specimen = ' Serum specimen ' WHERE kode = 'P0102';
UPDATE public.ref_lab SET kode_loinc = '94306-8', display_loinc = 'SARS-CoV-2 (COVID-19) N gene [Cycle Threshold #] in Specimen by NAA with probe detection', kode_specimen = '258500001', nama_specimen = 'Nasopharyngeal swab' WHERE kode = 'P010702';
UPDATE public.ref_lab SET kode_loinc = '94559-2', display_loinc = 'SARS-CoV-2 (COVID-19) ORF1ab region [Cycle Threshold #] in Specimen by NAA with probe detection', kode_specimen = '258500001', nama_specimen = 'Nasopharyngeal swab' WHERE kode = 'P010703';
UPDATE public.ref_lab SET kode_loinc = '54231-6', display_loinc = 'Spermatozoa morphology and motility panel - Semen', kode_specimen = '119347001', nama_specimen = 'Seminal fluid specimen' WHERE kode = 'S0102';
UPDATE public.ref_lab SET kode_loinc = '2571-8', display_loinc = 'Triglyceride [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'TG';
UPDATE public.ref_lab SET kode_loinc = '777-3', display_loinc = 'Platelets [#/volume] in Blood', kode_specimen = '119297000', nama_specimen = 'Blood specimen' WHERE kode = 'TRO';
UPDATE public.ref_lab SET kode_loinc = '24356-8', display_loinc = 'Urinalysis complete panel - Urine', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U0101';
UPDATE public.ref_lab SET kode_loinc = '5778-6', display_loinc = 'Color of Urine', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U010101';
UPDATE public.ref_lab SET kode_loinc = '5767-9', display_loinc = 'Appearance of Urine', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U010102';
UPDATE public.ref_lab SET kode_loinc = '5803-2', display_loinc = 'pH of Urine by Test strip', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U010103';
UPDATE public.ref_lab SET kode_loinc = '5811-5', display_loinc = 'Specific gravity of Urine by Test strip', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U010104';
UPDATE public.ref_lab SET kode_loinc = '5802-4', display_loinc = 'Nitrite [Presence] in Urine by Test strip', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U010105';
UPDATE public.ref_lab SET kode_loinc = '20454-5', display_loinc = 'Protein [Presence] in Urine by Test strip', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U010106';
UPDATE public.ref_lab SET kode_loinc = '25428-4', display_loinc = 'Glucose [Presence] in Urine by Test strip', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U010107';
UPDATE public.ref_lab SET kode_loinc = '2514-8', display_loinc = 'Ketones [Presence] in Urine by Test strip', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U010108';
UPDATE public.ref_lab SET kode_loinc = '20405-7', display_loinc = 'Urobilinogen [Mass/volume] in Urine by Test strip', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U010109';
UPDATE public.ref_lab SET kode_loinc = '5770-3', display_loinc = 'Bilirubin.total [Presence] in Urine by Test strip', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U010110';
UPDATE public.ref_lab SET kode_loinc = '5794-3', display_loinc = 'Hemoglobin [Presence] in Urine by Test strip', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U010111';
UPDATE public.ref_lab SET kode_loinc = '60017-1', display_loinc = 'Leukocyte esterase [Presence] in Urine by Test strip', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U010112';
UPDATE public.ref_lab SET kode_loinc = '24124-0', display_loinc = 'Microscopic observation in Urine sediment', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U010113';
UPDATE public.ref_lab SET kode_loinc = '5799-2', display_loinc = 'Erythrocytes [#/area] in Urine sediment by Microscopy high power field', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U01011301';
UPDATE public.ref_lab SET kode_loinc = '5821-4', display_loinc = 'Leukocytes [#/area] in Urine sediment by Microscopy high power field', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U01011302';
UPDATE public.ref_lab SET kode_loinc = '5788-5', display_loinc = 'Epithelial cells [#/area] in Urine sediment by Microscopy high power field', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U01011303';
UPDATE public.ref_lab SET kode_loinc = '24124-0', display_loinc = 'Casts [#/area] in Urine sediment by Microscopy high power field', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U01011304';
UPDATE public.ref_lab SET kode_loinc = '24124-0', display_loinc = 'Casts [#/area] in Urine sediment by Microscopy high power field', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U0101130401';
UPDATE public.ref_lab SET kode_loinc = '24124-0', display_loinc = 'Casts [#/area] in Urine sediment by Microscopy high power field', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U0101130402';
UPDATE public.ref_lab SET kode_loinc = '24124-0', display_loinc = 'Casts [#/area] in Urine sediment by Microscopy high power field', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U0101130403';
UPDATE public.ref_lab SET kode_loinc = '24124-0', display_loinc = 'Casts [#/area] in Urine sediment by Microscopy high power field', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U0101130404';
UPDATE public.ref_lab SET kode_loinc = '5782-8', display_loinc = 'Crystals [Type] in Urine sediment by Microscopy', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U01011305';
UPDATE public.ref_lab SET kode_loinc = '5769-5', display_loinc = 'Bacteria [#/area] in Urine sediment by Microscopy high power field', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U01011306';
UPDATE public.ref_lab SET kode_loinc = '18086-9', display_loinc = 'Other microscopic findings in Urine sediment', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U01011307';
UPDATE public.ref_lab SET kode_loinc = '25428-4', display_loinc = 'Glucose [Presence] in Urine by Test strip', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U0102';
UPDATE public.ref_lab SET kode_loinc = '20454-5', display_loinc = 'Protein [Presence] in Urine by Test strip', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U0103';
UPDATE public.ref_lab SET kode_loinc = '14957-5', display_loinc = 'Microalbumin [Mass/volume] in Urine', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U0106';
UPDATE public.ref_lab SET kode_loinc = '34543-9', display_loinc = 'Bilirubin direct and total panel [Mass/volume] - Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'U0108';
UPDATE public.ref_lab SET kode_loinc = '5802-4', display_loinc = 'Nitrite [Presence] in Urine by Test strip', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U0110';
UPDATE public.ref_lab SET kode_loinc = '5803-2', display_loinc = 'pH of Urine by Test strip', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U0111';
UPDATE public.ref_lab SET kode_loinc = '5811-5', display_loinc = 'Specific gravity of Urine by Test strip', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U0112';
UPDATE public.ref_lab SET kode_loinc = '2888-6', display_loinc = 'Protein [Mass/volume] in Urine', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U0114';
UPDATE public.ref_lab SET kode_loinc = '19123-9', display_loinc = 'Magnesium [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'U0115';
UPDATE public.ref_lab SET kode_loinc = '2106-3', display_loinc = 'Choriogonadotropin (pregnancy test) [Presence] in Urine', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U0117';
UPDATE public.ref_lab SET kode_loinc = '2106-3', display_loinc = 'Choriogonadotropin (pregnancy test) [Presence] in Urine', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U0118';
UPDATE public.ref_lab SET kode_loinc = '2106-3', display_loinc = 'Choriogonadotropin (pregnancy test) [Presence] in Urine', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U0119';
UPDATE public.ref_lab SET kode_loinc = '24356-8', display_loinc = 'Urinalysis routine panel - Urine', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U0135';
UPDATE public.ref_lab SET kode_loinc = '2106-3', display_loinc = 'Choriogonadotropin (pregnancy test) [Presence] in Urine', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U0136';
UPDATE public.ref_lab SET kode_loinc = '25428-4', display_loinc = 'Glucose 2 hours post meal in Urine', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U0140';
UPDATE public.ref_lab SET kode_loinc = '65750-2', display_loinc = 'Drug screen panel - Urine', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U0144';
UPDATE public.ref_lab SET kode_loinc = '19343-3', display_loinc = 'Amphetamine [Presence] in Urine by Screen test', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U014401';
UPDATE public.ref_lab SET kode_loinc = '14316-4', display_loinc = 'Benzodiazepines [Presence] in Urine by Screen test', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U014402';
UPDATE public.ref_lab SET kode_loinc = '19295-5', display_loinc = 'Morphine [Presence] in Urine by Screen test', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U014403';
UPDATE public.ref_lab SET kode_loinc = '14314-9', display_loinc = 'Cocaine [Presence] in Urine by Screen test', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U014404';
UPDATE public.ref_lab SET kode_loinc = '20521-1', display_loinc = 'Methamphetamine [Presence] in Urine by Screen test', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U014405';
UPDATE public.ref_lab SET kode_loinc = '19261-7', display_loinc = 'Cannabinoids [Presence] in Urine by Screen test', kode_specimen = '122575003', nama_specimen = 'Urine specimen' WHERE kode = 'U014406';
UPDATE public.ref_lab SET kode_loinc = '3084-1', display_loinc = 'Urate [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'UA';
UPDATE public.ref_lab SET kode_loinc = '3091-6', display_loinc = 'Blood urea nitrogen [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'UR';
UPDATE public.ref_lab SET kode_loinc = '3091-6', display_loinc = 'Blood urea nitrogen [Mass/volume] in Serum or Plasma', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'UREUM';
UPDATE public.ref_lab SET kode_loinc = '23007-8', display_loinc = 'Salmonella enterica serovar Typhi O Ab [Titer] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'W010101';
UPDATE public.ref_lab SET kode_loinc = '23007-8', display_loinc = 'Salmonella enterica serovar Typhi H Ab [Titer] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'W010102';
UPDATE public.ref_lab SET kode_loinc = '23009-4', display_loinc = 'Salmonella enterica serovar Paratyphi A O Ab [Titer] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'W010103';
UPDATE public.ref_lab SET kode_loinc = '23010-2', display_loinc = 'Salmonella enterica serovar Paratyphi A H Ab [Titer] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'W010104';
UPDATE public.ref_lab SET kode_loinc = '23011-0', display_loinc = 'Salmonella enterica serovar Paratyphi B O Ab [Titer] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'W010105';
UPDATE public.ref_lab SET kode_loinc = '23012-8', display_loinc = 'Salmonella enterica serovar Paratyphi B H Ab [Titer] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'W010106';
UPDATE public.ref_lab SET kode_loinc = '23013-6', display_loinc = 'Salmonella enterica serovar Paratyphi C O Ab [Titer] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'W010107';
UPDATE public.ref_lab SET kode_loinc = '23014-4', display_loinc = 'Salmonella enterica serovar Paratyphi C H Ab [Titer] in Serum', kode_specimen = '119364003', nama_specimen = 'Serum specimen' WHERE kode = 'W010108';